name: Build Gymanager WebView App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Create Directories
        run: |
          New-Item -Path "dist/Gymanager-win32-x64" -ItemType Directory -Force

      - name: Build WebView App
        run: |
          nativefier `
            --name "Gymanager" `
            --platform windows `
            --icon "${{ github.workspace }}/assets/gymanager.ico" `
            --out "${{ github.workspace }}/dist" `
            "https://www.gym.etecxperts.com" || exit 1

      - name: Package EXE
        run: |
          Compress-Archive `
            -Path "${{ github.workspace }}/dist/Gymanager-win32-x64/*" `
            -DestinationPath "${{ github.workspace }}/Gymanager.zip"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Gymanager-App
          path: |
            ${{ github.workspace }}/Gymanager.zip
            ${{ github.workspace }}/dist/Gymanager-win32-x64/Gymanager.exe
