name: Build Gymanager WebView App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'  # Consider using Node.js 20 (LTS)

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Build the WebView App
        run: nativefier --name "Gymanager" --platform windows --icon "./assets/gymanager.ico" "https://www.gym.etecxperts.com"

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4  # Updated to latest v4
        with:
          name: Gymanager-Windows-App
          path: Gymanager-win32-x64/
